### ISSUE TITLE
Is this still working for you?

### ISSUE THREAD

**Issue by kenjfox** [Vendo232/wyze_v3_frigate_http_stream#1]
Just curious if this is still working for you.  I've been following other github repos with wyze hacks, and it looks like wyze is becoming less and less friendly to customized setups like this.  I've spent too much time trying to get 4 cameras to work well via rtsp- am contemplating spending a bit more money for IP cams that better support standard protocols.  Would appreciate any insights you may have.

**Comment by Vendo232** [comment]
The best bet is to move away from Wyze, I have already started migration to Armrest PoE 5MP, these are cheap and awesome cameras and mainly no issues!!!. No reboots, no fwnipdates, they just work.

For my remaining V3s Iam using Wyze mini- hacks it allows to use PoE Ethernet for data as well and it does help as wifi is not reliable for HD streams. It is relatively stable but it makes an effort and time compared to Armcrest

This guide is deprecated

**Comment by kenjfox** [comment]
Okay thanks very much for the feedback- greatly appreciated.
